FROM itamararjuan/go-node

#WORKDIR /go/src/github.com/orbs-network/orbs-ethereum-contracts/asb
#ADD . /go/src/github.com/orbs-network/orbs-ethereum-contracts/asb
#RUN go get -u github.com/orbs-network/orbs-ethereum-contracts/...
#RUN cd ~/go/src/github.com/orbs-network/orbs-ethereum-contracts/

#COPY ./build ./asb/build

#RUN cd asb

#RUN yarn

#RUN sh -x ganache_full.sh
